# Generated by Django 4.2.4 on 2023-08-22 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dogs', '0002_dog_is_public_dog_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='dog',
            name='price',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
