# Generated by Django 4.2.4 on 2023-08-22 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dogs', '0003_dog_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dog',
            name='price',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
